/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Alive */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @enum {string} */
                            status: "ok" | "degraded";
                            /** @description Number of cards in the index */
                            cards: number;
                            /** @description asmDB engine version */
                            engine: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The card of the day, plus the countdown to the next one */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Today's bloom */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            card: components["schemas"]["Card"];
                            /**
                             * Format: date-time
                             * @description Next 10:00 Europe/Paris
                             */
                            nextBloomAt: string;
                            secondsUntilNext: number;
                            /** @description How many slimes have bloomed so far */
                            dayNumber: number;
                        };
                    };
                };
                /** @description No card has bloomed today yet */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated SLIMEDEX, served from the in-memory index */
        get: {
            parameters: {
                query?: {
                    page?: number;
                    size?: number;
                    type?: components["schemas"]["SlimeType"];
                    rarity?: components["schemas"]["Rarity"];
                    sort?: "newest" | "oldest" | "rarest" | "happiest";
                    /** @description Case-insensitive name search */
                    q?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A page of cards */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            items: components["schemas"]["CardSummary"][];
                            page: number;
                            size: number;
                            total: number;
                            hasMore: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One fully decoded card */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serial: components["parameters"]["Serial"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The card */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Card"];
                    };
                };
                /** @description No such card */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{serial}/raw": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The PSC-1 payload exactly as it lives in asmDB — the provenance view */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serial: components["parameters"]["Serial"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Raw rows plus their decoding */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @description The asmDB rows verbatim. Integers are strings, as asmDB returns them. */
                            rows: {
                                /** @example 16 */
                                id: string;
                                /** @example 20260728 */
                                value: string;
                                /** @example psc.1.0 */
                                tag: string;
                                /** @description Z85 */
                                content: string;
                            }[];
                            /** @description Length of the PSC-1 stream before Z85 */
                            streamBytes: number;
                            rowCount: number;
                            /** @description keccak256 of the stream — what is minted on-chain */
                            cardHash: string;
                            decoded: components["schemas"]["Card"];
                        };
                    };
                };
                /** @description No such card */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Error"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{serial}/image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The card PNG, proxied from private Blob Storage */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serial: components["parameters"]["Serial"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 1024x1536 PNG with alpha */
                200: {
                    headers: {
                        "Cache-Control"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "image/png": string;
                    };
                };
                /** @description No such card */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{serial}/thumb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The 512x768 WebP thumbnail */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serial: components["parameters"]["Serial"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description WebP thumbnail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "image/webp": string;
                    };
                };
                /** @description No such card */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Collection-wide counters */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Stats */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total: number;
                            byRarity: {
                                [key: string]: number;
                            };
                            byType: {
                                [key: string]: number;
                            };
                            /** @description SMILE left in the Genesis Rain */
                            genesisRemaining: number;
                            /** @description Slimes that can still be minted */
                            bloomsRemaining: number;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nft/{serial}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ERC-721 metadata for the card */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    serial: components["parameters"]["Serial"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description ERC-721 metadata document */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            name: string;
                            description: string;
                            /** Format: uri */
                            image: string;
                            /** Format: uri */
                            external_url?: string;
                            attributes: {
                                trait_type?: string;
                                value?: unknown;
                                display_type?: string;
                            }[];
                        };
                    };
                };
                /** @description No such card */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger a generation by hand. Off by default. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        forceRarity?: components["schemas"]["Rarity"];
                        /** @default false */
                        dryRun?: boolean;
                    };
                };
            };
            responses: {
                /** @description Generation accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing or wrong admin token */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description A card already exists for today */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        Rarity: "COMMON" | "UNCOMMON" | "RARE" | "EPIC" | "LEGENDARY" | "MYTHIC";
        /** @enum {string} */
        SlimeType: "FAIRY" | "FOREST" | "WATER" | "EMBER" | "STORM" | "STONE" | "SUGAR" | "GHOST" | "METAL" | "COSMIC" | "BLOOM" | "FROST" | "SLUDGE" | "BEAM" | "PAPER" | "DREAM";
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        /** @description What the gallery grid needs, and nothing more. */
        CardSummary: {
            serial: number;
            /** @example PS-0001 */
            cardId: string;
            name: string;
            level: number;
            rarity: components["schemas"]["Rarity"];
            type: components["schemas"]["SlimeType"];
            shiny?: boolean;
            /** Format: date */
            mintDate: string;
            thumbUrl: string;
            onChain?: boolean;
        };
        /** @description The full card. Mirrors contracts/card.schema.json plus derived display fields. */
        Card: {
            serial: number;
            /** @example PS-0001 */
            cardId: string;
            name: string;
            level: number;
            rarity: components["schemas"]["Rarity"];
            /** @example Aurora */
            rarityHouse?: string;
            type: components["schemas"]["SlimeType"];
            shiny?: boolean;
            height_mm: number;
            weight_g: number;
            strength: number;
            endurance: number;
            agility: number;
            happiness: number;
            personality: string;
            power_name: string;
            power_desc: string;
            quote: string;
            biome?: string;
            companion?: string;
            /** Format: date */
            mintDate: string;
            dayNumber?: number;
            imageUrl: string;
            thumbUrl: string;
            /** @description Dominant colours of the artwork, so the UI can tint itself to the card. */
            palette?: string[];
            chain?: {
                tokenId?: number;
                txHash?: string;
                blockNumber?: number;
                /** Format: uri */
                explorerUrl?: string;
            } | null;
        };
    };
    responses: never;
    parameters: {
        Serial: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
