/**
 * MSW browser worker. Started from src/main.tsx before React renders, but only when
 * VITE_USE_MOCK is on. The service-worker script itself lives at public/mockServiceWorker.js
 * (generated by `npx msw init public`).
 */
import { setupWorker } from 'msw/browser';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
